# Default values for jenkins-swarm-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 749474515584.dkr.ecr.eu-central-1.amazonaws.com/systemteam/jenkins-swarm
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

jenkinsSwarmConfig:
  master: https://172.20.3.79
  masterIP: "172.20.3.79"
  username: manuele.fanelli@wolterskluwer.com  #THE USER ASSOCIATED WITH THE TOKEN
  password: 11d141bb44f54cda15e897992d3cc58a20 #USE THE JENKINS API TOKEN
  executorName: executor_PARIS
  labels: "devxeuw3"
  otherOptions: "-disableSslVerification -fsroot /home/jenkins"



serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
