{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jenkins-swarm-client.serviceAccountName" . }}
  labels:
    {{- include "jenkins-swarm-client.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
# This is a big ass security issue. You should enforce it.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jenkins-swarm-client.serviceAccountName" . }}-clusterrole
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jenkins-swarm-client.serviceAccountName" . }}-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jenkins-swarm-client.serviceAccountName" . }}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "jenkins-swarm-client.serviceAccountName" . }}
  namespace: ml-runner
{{- end }}
